version: '3'
services:
  db:
    image: mysql:8.0.16
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3316:3306

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:password@mysql:3306
    volumes:
      - .:/t-farm
      - bundle:/usr/local/bundle
      - tmp-data:/t-farm/tmp
      - public-data:/t-farm/public
    tty: true
    stdin_open: true
    #ports:
    #  - 3000:3000
    depends_on:
      - db
      - chrome
    links:
      - db:mysql
  
  server:
    build:
      context: containers/nginx
    volumes: 
      - public-data:/t-farm/public
      - tmp-data:/t-farm/tmp
      - ./log/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - web

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-yttrium
    ports:
      - 4444:4444
      - 5900:5900
  
volumes:
  mysql-data:
    driver: local
  bundle:
  public-data:
  tmp-data: