version: '3'
services:
  db:
    image: mysql:8.0.16
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3316:3306'
    networks:
      test-network:
        aliases:
          - db.com
          

  web:
    build: 
     context: .
     dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: mysql2://root:password@mysql:3306
    volumes:
      - .:/t-farm
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    links:
      - db:mysql
    networks:
      test-network:
        aliases:
          - web.com

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-yttrium
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      test-network:
        aliases:
          - chrome.com

volumes:
  mysql-data:
    driver: local
  bundle:

networks:
  test-network: